### ISSUE TITLE
add minio s3 examples

### ISSUE THREAD

**Issue by DyfanJones** [DyfanJones/s3fs#2]

**Comment by jkh1** [comment]
Trying to use s3fs to access files on a minio server with code like this:
```
s3_file_system(aws_access_key_id = "key_id",  
               aws_secret_access_key = "secret_key", 
               region_name = "", 
               endpoint = "https://example.com",
               s3_force_path_style = TRUE) 
s3_file_info("bucket_name/file_name")
```
results in 
`
Error in get_region(cfgs$credentials$profile) : No region provided
`
It looks as if whatever is given as region_name is ignored. Is this a bug or am I going about it wrong?

Thx

**Comment by DyfanJones** [comment]
hi @jkh1,

Sorry about the delay in the minio s3 example. If you remove the `region_name` it should work.  Here is an example of me creating minio s3 on my local machine :)

``` r
library(s3fs)

s3_file_system(
  aws_access_key_id = "minioadmin",  
  aws_secret_access_key = "minioadmin", 
  endpoint = "http://localhost:9000"
)

s3_dir_ls()
#> [1] ""

s3_bucket_create("s3://testbucket")
#> [1] "s3://testbucket"

# refresh cache
s3_dir_ls(refresh = T)
#> [1] "s3://testbucket"

s3_bucket_delete("s3://testbucket")
#> [1] "s3://testbucket"

# refresh cache
s3_dir_ls(refresh = T)
#> [1] ""
```

<sup>Created on 2022-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Please let me know if your having any difficulty :)

I will add this example to the readme 😄

**Comment by DyfanJones** [comment]
Ah I see, I guess you haven't set up any .aws/credentials or .aws/config files.  No worries you can set a default aws region for example: `us-east-1` and it should connect file.

``` r
library(s3fs)

s3_file_system(
  aws_access_key_id = "minioadmin",  
  aws_secret_access_key = "minioadmin",
  region = "us-east-1",
  endpoint = "http://localhost:9000",
  refresh = T
)

s3_dir_ls()
#> [1] ""

s3_bucket_create("s3://testbucket")
#> [1] "s3://testbucket"

# refresh cache
s3_dir_ls(refresh = T)
#> [1] "s3://testbucket"

s3_bucket_delete("s3://testbucket")
#> [1] "s3://testbucket"

# refresh cache
s3_dir_ls(refresh = T)
#> [1] ""
```

<sup>Created on 2022-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I wonder if I should set that as a backup if it fails to get an aws region 🤔

**Comment by jkh1** [comment]
This works  although I had tried us-east-1 before, maybe the refresh option did the trick. Thanks.

**Comment by DyfanJones** [comment]
@jkh1 I have set a default region so you shouldn't get that error again :) I have also added the minio s3 example. please feel free to re-open this ticket if you come across the same issue again.
