### ISSUE TITLE
Inconsistent result of s3fs::s3_dir_create with fs::dir_create

### ISSUE THREAD

**Issue by reisfe** [DyfanJones/s3fs#28]
When the directory already exists, fs::dir_create ignores it and returns the path(s) to the directory(ies), while s3fs::s3_dir_create returns the string "Directory already exists in AWS S3".

If the goal is to make code written using the fs package portable to the s3fs than the behavior of the functions should be as close as possible.

Also, returning a string is not the most common behavior in R. A condition should be raised, either error, warning or message.

**Comment by DyfanJones** [comment]
In the meantime I welcome any PRs :) they help me greatly when I judge my open source packages 😄

**Comment by DyfanJones** [comment]
Sorry for the delay in this. PR #30 addresses issue. I will release it to the cran shortly

**Comment by reisfe** [comment]
Great!
Thank you.
(And thank you for the great package.)

**Comment by DyfanJones** [comment]
Closing as s3fs 0.1.4 has been released to the cran
