### ISSUE TITLE
undeclared dependency on R version >= 3.6.0

### ISSUE THREAD

**Issue by tyner** [DyfanJones/s3fs#29]
Some functions in the `s3fs` package make use of `base::trimws` with the `whitespace` argument. However, that argument is not available prior to R version 3.6.0.

So in older R versions:
```r
foo <- s3_dir_ls("s3://foo/bar")
```
gives:
```
Error in trimws(path, which = "right", whitespace = "/") : 
  unused argument (whitespace = "/")
```

**Comment by DyfanJones** [comment]
Ah sorry about that. I guess I should include the package `backport` to ensure that all functions are available for old versions of R. I am currently on holiday at the moment, so will tackle this when I get back :) in the mean time I am open to any PRs :)

**Comment by tyner** [comment]
Rather than add a dependency on another package, my personal preference would be to explicitly declare the version dependency and move on.

**Comment by DyfanJones** [comment]
That is fair :)

**Comment by DyfanJones** [comment]
Sorry for the delay in this. PR #30 addresses issue. I will release it to the cran shortly

**Comment by DyfanJones** [comment]
Closing as s3fs 0.1.4 has been released to the cran
