### ISSUE TITLE
I can't save files to a Minio bucket any longer on SerializationError (HTTP 400)

### ISSUE THREAD

**Issue by asitemade4u** [DyfanJones/s3fs#40]
Hi,
Thank you for the very useful package!

First, **let me be clear**: the error is probably NOT a bug of the package, but mine.
I just would like to have some insights on the reason of the error. From what I read on the Web, the error could be caused by a firewall.

- I have used `s3fs` without a glitch with self-hosted Minio for months.
- Then, suddenly, approx. 3 weeks ago, I have been unable to save any file into buckets.

The error is: 
```error
Error: SerializationError (HTTP 400). failed to read from query HTTP response body
```

I have checked everything:
- Minio secrets
- my code which did not change
- the type of file involved
- I have sanitized the filename to save
- `curl -I http://[my_minio_server_IP]:9000/minio/health/live` returns OK

To no avail.
Please help,
S.

**Comment by DyfanJones** [comment]
Did it work with paws.common 0.7.0? Or it was working with 0.7.1 and then it broke?

**Comment by DyfanJones** [comment]
Can you try with paws.conmon 0.7.0. just want to rule out version 0.7.1 is causing the issue.

**Comment by DyfanJones** [comment]
> So:
> 
> * I installed `paws.common` 0.7.0
> * I `renv::snapshot()` the installation and checked version 0.7.0 was now loaded
> * to be really sure, I rebooted the server and checked `sessionInfo()`
> 
> And SORRY, still not working...

That is good as it means a bug didn't appear from 0.7.0 to 0.7.1

**Comment by DyfanJones** [comment]
I will look into this over the weekend if that is ok. I am currently on holiday and my son's birthday is tomorrow. Apologies in advance for the delay investing this and fixing it.

**Comment by DyfanJones** [comment]
In the meantime there are a few things can you check out. Check paws logs, it can be set in `options(paws.log_level=3)`. 

Has anything changed in the last 3 weeks that could of caused this issue to pop up.

Can you include your minio version so I can reproduce

Is it only upload file that is causing the issue or all s3fs operations with minio are broken?

**Comment by DyfanJones** [comment]
I wonder if the issue is down to not getting the correct credentials and caching the wrong ones. Can you try:

```r
s3_file_system(
  aws_access_key_id = Sys.getenv("MINIO_KEY"),
  aws_secret_access_key = Sys.getenv("MINIO_PWD"),
  endpoint = glue::glue("http://{theenv$miosrv}")
  refresh = TRUE
)
```

This will refresh the cached session. 

Error messages like this one:

Error: AccessDenied (HTTP 403). Access Denied.

Makes me think of issue with credentials.

**Comment by DyfanJones** [comment]
Just had a look through your code and it looks like your doing a http url for your destination. For `s3_file_upload` it needs to be a s3 uri. So if you  try changing the http url to an s3 uri.

```r
# from 
dstpth <- glue::glue("http://192.168.1.221:9000/{dstbkt}/test/{fs::path_sanitize(filnam)}.{filext}")

# to
dstpth <- glue::glue("s3://{dstbkt}/test/{fs::path_sanitize(filnam)}.{filext}")
```

Let me know if this code works for you :)
> ```r
> # NOTE: Create temporary file
> tmpnam <- dattim() # gives a unique file name with digits from date and time
> tmppth <- glue::glue("/run/user/1000/{fs::path_sanitize(tmpnam)}.csv")
> tibble::tribble(
>     ~zaz, ~zoz,
>     "aaa", "aa1",
>     "bbb", "aa1",
>     "ccc", "aa1",
>     "ddd", "aa1"
> ) |>
>     readr::write_csv(tmppth)
> # NOTE: Write to destination Minio server, into bucket `mau`
> filnam <- "zaza"
> pthtmp <- tmppth
> filext <- "csv"
> dstbkt <- "mau/test"
> dstpth <- glue::glue("s3://{dstbkt}/test/{fs::path_sanitize(filnam)}.{filext}")
> # NOTE: Transfer to Minio
> theflg <- TRUE
> tryCatch(
>     expr = {
>         # NOTE: If successful, delete the temporary file
>         s3fs::s3_file_upload(path = pthtmp, new_path = dstpth, overwrite = TRUE)
>         print(glue::glue("{filext} file saved in Minio: {dstpth}"))
>         fs::file_delete(pthtmp)
>     },
>     error = function(e) {
>         print(glue::glue("s3fs could not save file to Minio '{dstbkt}' bucket.\nReported error: {e}"))
>         theflg <- FALSE
>     }
> )
> ```

**Comment by DyfanJones** [comment]
Ok cool :) I will have a look at minio over the weekend :) just need to get it up and running on my machine again :D

**Comment by DyfanJones** [comment]
I noticed there was an issue regarding custom endpoints when loading them in from config file https://github.com/paws-r/paws/pull/768

```r
remotes::install_github("dyfanjones/paws/paws.common@custom_endpoint")
```

After this patch I am not noticing the issue you are having.

``` r
library(s3fs)
# NOTE: Create temporary file
tmp_file <- tempfile()
tibble::tribble(
  ~zaz, ~zoz,
  "aaa", "aa1",
  "bbb", "aa1",
  "ccc", "aa1",
  "ddd", "aa1"
) |>
  readr::write_csv(tmp_file)

# Set s3fs file system profile
s3_file_system(profile_name = "minio")

bucket <- s3_path("test-bucket")
dstpth <- s3_path(bucket, "test/demo_1.csv")

s3_file_upload(path = tmp_file, new_path = dstpth, overwrite = T)
#> [1] "s3://test-bucket/test/demo_1.csv"
s3_dir_ls(bucket, recurse = T)
#> [1] "s3://test-bucket/test/demo_1.csv"
```

<sup>Created on 2024-04-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

You could try seeing if the presigned url is getting generated correctly. Here is how you create a presigned url using paws with signature `s3v4`.

```r
library(paws)
client <- s3(config(credentials(profile = "minio"), signature_version = "s3v4"))
client$generate_presigned_url("list_objects", params = list(Bucket = "demo"))
```
You could also double check if your credentials are getting passed correctly to paws as this could be an issue as well :)

**Comment by DyfanJones** [comment]
You don't need to define the path to minio server when it is in config file. Similar how you set up a normal connection to aws. 

Presigned url generates the url when calling minio or aws. And return the url before sending it. This allows you to double check if url has been created correctly.

Note the latest version of paws.common has been released to the cran. Let me know if that helps you at all :)

**Comment by DyfanJones** [comment]
I am guessing you haven't set up a profile called `minio` to cause the errors you are coming into (for the above example https://github.com/DyfanJones/s3fs/issues/40#issuecomment-2034202936):
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

Default profile example:
.aws/credentials
```
[default]
aws_access_key_id = minioadmin
aws_secret_access_key = minioadmin
```

.aws/config
```
[default]
output = json
endpoint_url = http://127.0.0.1:9000
```

As we are using the default profile you don't need to make any changes to `s3fs::s3_file_system` i.e. https://github.com/DyfanJones/s3fs/issues/40#issuecomment-2034202936

```r
s3fs::s3_file_url("s3://demo-bucket/test/demo_1.csv")
#> "http://127.0.0.1:9000/demo-bucket/test/demo_1.csv?AWSAccessKeyId=minioadmin&Expires=1713266952&Signature=uv4beW4N13CzzIPSo3RMCpO2qCI%3D"
```

As we can see the credentials are coming through and the endpoint it set correctly :)

**Comment by DyfanJones** [comment]
@asitemade4u  this would be down to `s3fs::s3_file_system()` already being initialised and you will have to refresh the connection: https://dyfanjones.github.io/s3fs/reference/s3_file_system.html
