### ISSUE TITLE
Warning in `s3fs::s3_file_delete()` when deleting file from Backblaze B2

### ISSUE THREAD

**Issue by salim-b** [DyfanJones/s3fs#42]
When deleting a file from Backblaze B2 via [`s3fs::s3_file_delete()`](https://dyfanjones.github.io/s3fs/reference/delete.html), I observe the following warning:

```
Warning message:
In rbindlist(lapply(resp$Versions, function(v) list(size = v$Size,  :
  Column 3 ['owner'] of item 1 is length 0. This (and 0 others like it) has been filled with NA (NULL for list columns) to make each item uniform.
```

The file is deleted successfully and the function returns the input `path` as expected. I didn't test other object storage providers besides Backblaze B2.

The output indicates that the warning is thrown here:

https://github.com/DyfanJones/s3fs/blob/a9052902b33f8d80c49f2476809bf4a7741fa84d/R/s3filesystem_class.R#L1048-L1058

Since multiple data.table calls are already wrapped in `suppressWarnings()` in that file, I dared to submit https://github.com/DyfanJones/s3fs/pull/43 that suppresses the above warning.

A discussion from dplyr development about how to properly handle cases where `data.table::rbindlist()` throws this warning is found [here](https://github.com/tidyverse/dplyr/issues/5429).

**Comment by DyfanJones** [comment]
Will keep this open until cran release :)

**Comment by DyfanJones** [comment]
s3fs 0.1.6 has been released to the cran
