### ISSUE TITLE
Files without extensions will be created as a `dir/file` instead of `file`

### ISSUE THREAD

**Issue by pat-s** [DyfanJones/s3fs#47]
Hi!

First, thanks a lot for this package. It has made my interactions with S3 backends much easier compared to using {paws}.

I noticed the following niche issue when uploading a file without extension using `s3_file_upload()`: 

Assuming a remote path of `$BUCKET/my/file`, the resulting file will be created as `$BUCKET/my/file/file` - instead of `$BUCKET/my/file`.
When using `paws.storage::s3()$put_object()` directly, this is not the case (i.e. it works as intended) and `$BUCKET/my/file` gets created.

**Comment by DyfanJones** [comment]
Ah sorry about that. I am currently jumping between open source projects. Happy to receive PR's so if you are able to find the issue first please feel free to raise a PR. I am really grateful for any contributions :)

**Comment by pat-s** [comment]
Ah no worries! 
I can use {paws} in the meantime, as it is only one file that is affected by this.

Just wanted to let you (and others) know as it took me a while to get the idea that it could be a package problem and not a generic S3 one :)

**Comment by DyfanJones** [comment]
Managed to squeeze sometime in :D @pat-s can you give dev version ago

```r
remotes::install_github("dyfanjones/s3fs", ref = "file_upload")
```

**Comment by pat-s** [comment]
Thanks again, would appreciate a CRAN release if you have time (and maybe more changes than only this one) :)
